# Generated by Django 3.1.7 on 2021-08-17 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prereghos',
            name='allocate_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.sales', unique=True),
        ),
    ]
