# Generated by Django 3.1.7 on 2021-08-17 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
        ('hospital', '0002_auto_20210817_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prereghos',
            name='allocate_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.sales'),
        ),
        migrations.AlterField(
            model_name='prereghos',
            name='hospital_name',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
