# Generated by Django 3.1.7 on 2021-08-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_auto_20210817_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prereghos',
            name='hospital_name',
            field=models.CharField(max_length=80),
        ),
    ]
